[package]
name = "lorawan-demo"
version = "0.1.0"
authors = ["Henk Dieter Oordt <henkdieter@oordt.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { version = "0.2.3", features = ["unproven"] }


[features]
default = ["sx126x"]
sx126x = []
sx127x = []
